### ISSUE TITLE
Weighting data model

### ISSUE THREAD

**Issue by ivanmauricio** [ParkisonsUK-fuse/what3things#25] opened 2017-03-27 13:38 UTC
We need to decide how best to represent the weighting of options and how this matches up to services.

The initial idea from the product team is to have a primary and a number of secondary services for each quote. 

Links #15

**Comment by andrewMacmurray** [comment] 2017-03-28 16:50
closing as duplicate of #15

**Closed by andrewMacmurray** 2017-03-28 16:50 UTC
Labels: data, duplicate, question
